### ISSUE TITLE
Use ToiletDB to store Vue/React state?

### ISSUE THREAD

**Issue by Snazzyham** [maxogden/toiletdb#11]
My apologies if this is a dumb question, I'm currently building a simple app and was wondering if there would be anyway to persist a vue components data / a react components state in toiletDB?

**Comment by joehand** [comment]
Yes! That is our use case as well, we use this in [dat-desktop](https://github.com/datproject/dat-desktop) to persist *some* state. Until #9 is merged, it will not support subobjects which may be quite limiting.

If you want to persist to a file, this would work well but it'll need to be accessible for your app (probably not great for a browser application). If you want to persist it to a database, local storage provides a pretty good key value store in the browser. I'm not 100% up on react stuff but there may be modules a bit more focused on that use case.
