### ISSUE TITLE
'Error: EPERM: operation not permitted' running 'dat create'

### ISSUE THREAD

**Issue by henry-luo** [maxogden/toiletdb#16]
I just installed DAT and tried to initialize a repository with 'dat create' command. And experienced error like below:
```
{ Error: EPERM: operation not permitted, rename 'D:\...\dat.json.0.6862932466069354' -> 'D:\...\dat.json'
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'D:\\...\\dat.json.0.6862932466069354',
  dest: 'D:\\...\\dat.json' }
```
As I googled on the Internet for [similar bug reports](https://github.com/isaacs/node-graceful-fs/issues/104) and traced down the source code. I confirmed the bug is related to the code in toiletdb.

In the in the [write()](https://github.com/maxogden/toiletdb/blob/master/index.js) method, the code is using `db.fs.writeFile()`, then followed by `db.fs.rename()`, which can lead to a **race condition**, if `rename()` starts before `writeFile()` finishes, and caused the error I experienced above. After I changed `writeFile()` to `writeFileSync()`, the problem is resolved on my machine.

The code after change:
```
      db.fs.writeFileSync(tmpname, payload, function (err) {
        if (err) {
          return db.fs.unlink(tmpname, function () {
            cb(err)
          })
        }
      });
     db.fs.rename(tmpname, db.name, cb);
```
The root issue might be in node fs. But changing to `writeFileSync `makes toiletdb more robust.

**Comment by joehand** [comment]
Thanks, I'll check it out! Same bug in Dat repo: https://github.com/datproject/dat/issues/891
