### ISSUE TITLE
durability

### ISSUE THREAD

**Issue by dominictarr** [maxogden/toiletdb#2]
instead of just writing the file, it might be better to write to a second file (say, `filename+'~'`) then rename that file to the normal filename.

When a `toiletdb` gets large, it's conceivable that the computer crashes halfway through a write (unlikely, but possible) if you only move the file after the write succeeds, then you'll have durability.

I used this approach in https://github.com/flumedb/atomic-file

**Comment by max-mapper** [comment]
published in 1.2.1
